# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HSFKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HSFKitDemo

  target 'HSFKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HSFKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  
  
  pod 'SVProgressHUD'#HUD
  pod 'XHToast'#文本小提示HUD

end
